[character]
success_symbol = "ğŸ°ğŸ°ğŸ°ğŸ°ğŸ°ğŸ°"

[directory]
truncation_length = 100
truncate_to_repo = true

[package]
disabled = true

[time]
disabled = false
format = "ğŸ•[ %T ]"
utc_time_offset = "-5"
time_range = "10:00:00-14:00:00"

[NodeJS]
symbol = "â¬¢"
style = "bold green"
disabled = false
not_capable_style = "bold red"

[docker_context]
symbol = "ğŸ³"

[php]
symbol = "ğŸ”¹"

[aws]
style = "bold blue"
symbol = "ğŸ…°"
displayed_items = "region"
[aws.region_aliases]
ap-southeast-2 = "au"
us-east-1 = "va"

[git_branch]
symbol = "ğŸŒ±"
truncation_length = 20
truncation_symbol = ""

[git_commit]
symbol = "â«"
truncation_length = 30

[git_state]
progress_divider = " off "
cherry_pick = "ğŸ’ PICKING"

[git_status]
conflicted = "ğŸ³ï¸"
ahead = "ğŸš—ğŸ’¨"
behind= "ğŸ˜°"
diverged = "ğŸ˜µ"
untracked = "ğŸ¤·ğŸ¼<200d>"
stashed = "ğŸ“¦"
modified = "ğŸ“"
staged = "++"
renamed = "ğŸ”¥"
delete = "ğŸ—‘"
